core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("usuarios.urls")),
    path("", include("servicos.urls")),
    path("", include("agendamentos.urls")),
    path("avaliacoes/", include("avaliacoes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns += debug_toolbar_urls()

agendamentos/models.py
from datetime import datetime, timedelta

from dateutil.rrule import DAILY, MONTHLY, WEEKLY, rrule
from django.db import models
from django.utils import timezone


class Agendamento(models.Model):
    profissional = models.ForeignKey(
        "usuarios.Profissional",
        on_delete=models.CASCADE,
    )
    cliente = models.ForeignKey(
        "usuarios.Cliente",
        on_delete=models.CASCADE,
    )
    horario = models.ForeignKey("Horario", on_delete=models.CASCADE)
    status_choices = (
        ("Pendente", "Pendente"),
        ("Concluido", "Concluido"),
        ("Cancelado", "Cancelado"),
    )
    status = models.CharField(
        max_length=9,
        choices=status_choices,
        default="Pendente",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.profissional.servico.nome} - {self.cliente}"


class Horario(models.Model):
    profissional = models.ForeignKey(
        "usuarios.Profissional",
        on_delete=models.CASCADE,
    )
    data_inicio = models.DateTimeField()
    data_fim = models.DateTimeField()
    vago = models.BooleanField(default=True)

    FREQUENCIA_CHOICES = [
        ("UNICA", "Não se repete"),
        ("DIARIA", "Todos os dias"),
        ("SEMANAL", "Semanalmente"),
        ("MENSAL", "Mensalmente"),
    ]
    frequencia = models.CharField(
        max_length=10,
        choices=FREQUENCIA_CHOICES,
        default="UNICA",
    )

    dias_semana = models.CharField(max_length=13, blank=True, null=True)
    data_fim_recorrencia = models.DateField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.data_inicio}"

    def gerar_horarios_recorrentes(self):
        if self.frequencia == "UNICA":
            return [self]

        duracao = self.data_fim - self.data_inicio

        proximo_ano = (self.data_inicio + timedelta(days=365)).date()

        data_fim_recorrencia = self.data_fim_recorrencia or proximo_ano

        if self.data_inicio.tzinfo is None:
            self.data_inicio = timezone.make_aware(self.data_inicio)

        if self.data_fim.tzinfo is None:
            self.data_fim = timezone.make_aware(self.data_fim)

        data_fim_recorrencia = timezone.make_aware(
            datetime.combine(data_fim_recorrencia, self.data_inicio.time()),
        )

        if self.frequencia == "DIARIA":
            datas = list(
                rrule(DAILY, dtstart=self.data_inicio, until=data_fim_recorrencia),
            )
        elif self.frequencia == "SEMANAL":
            dias_semana = (
                [int(dia) for dia in self.dias_semana.split(",")]
                if self.dias_semana
                else None
            )
            datas = list(
                rrule(
                    WEEKLY,
                    dtstart=self.data_inicio,
                    until=data_fim_recorrencia,
                    byweekday=dias_semana,
                ),
            )
        elif self.frequencia == "MENSAL":
            datas = list(
                rrule(MONTHLY, dtstart=self.data_inicio, until=data_fim_recorrencia),
            )
        else:
            return []

        horarios_recorrentes = [
            Horario(
                profissional=self.profissional,
                data_inicio=data,
                data_fim=data + duracao,
                vago=True,
                frequencia="UNICA",
            )
            for data in datas[1:]
        ]

        return horarios_recorrentes

avaliacoes/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class Avaliacao(models.Model):
    nota = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    comentario = models.TextField()
    cliente = models.ForeignKey("usuarios.Cliente", on_delete=models.CASCADE)
    profissional = models.ForeignKey("usuarios.Profissional", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    agendamento = models.OneToOneField(
        "agendamentos.Agendamento", on_delete=models.CASCADE
    )

    def __str__(self) -> str:
        return self.comentario

templates/partials/aside.html
<div data-menu-background class="bg-zinc-800 fixed inset-0 opacity-75 hidden z-10"></div>
<aside data-menu class="bg-blue-700 min-w-80 h-screen flex flex-col fixed top-0 pt-16 right-full transition-all z-20 overflow-auto">
  <span data-menu-close class="text-[3rem] w-8 h-8 leading-8 text-white absolute top-4 right-4 cursor-pointer">
    &times;
  </span>
    {% if is_profissional_autenticado %}
      <section data-expandable-container class="p-4 flex flex-col gap-2 rounded-md">
        <h2 class="text-white text-xl">Agendamentos</h2>
        {% if meus_agendamentos %}
          <ul data-expandable-list class="flex flex-col gap-2 max-h-40 overflow-hidden transition-all">
            {% for agendamento in meus_agendamentos %}
            <li>
                {% include 'agendamentos/partials/appointment_card.html' with date=agendamento.horario.data_inicio|date:"d/m" start_time=agendamento.horario.data_inicio|date:"H:i" end_time=agendamento.horario.data_fim|date:"H:i" %}
              </li>
            {% endfor %}
          </ul>
          {% if meus_agendamentos|length > MAX_ITENS_CONTAINER_EXPANSIVEL %}
            <div class="flex w-full justify-center items-center text-sm pt-2">
              <span
                data-expandable-button
                class="text-white cursor-pointer hover:scale-105 transition-transform"
              >
                Ver Mais ↓
              </span>
            </div>
          {% endif %}
        {% else %}
          <p class="text-white p-4">Nenhum agendamento cadastrado</p>
        {% endif %}
      </section>
      <section data-expandable-container class="p-4 flex flex-col gap-2 rounded-md">
        <h2 class="text-white text-xl">Horários</h2>
          {% if meus_horarios %}
            <ul data-expandable-list class="flex flex-col gap-2 max-h-40 overflow-hidden transition-all">
              {% for horario in meus_horarios %}
                <li {% if not horario.vago %} class="cursor-not-allowed opacity-50" {% endif %}>
                  {% include 'agendamentos/partials/schedule_card.html' with date=horario.data_inicio|date:"d/m" start_time=horario.data_inicio|date:"H:i" end_time=horario.data_fim|date:"H:i" %}
                </li>
              {% endfor %}
            </ul>
            {% if meus_horarios|length > MAX_ITENS_CONTAINER_EXPANSIVEL %}
              <div class="flex w-full justify-center items-center text-sm pt-2">
                <span
                  data-expandable-button
                  class="text-white cursor-pointer hover:scale-105 transition-transform"
                >
                  Ver Mais ↓
                </span>
              </div>
            {% endif %}
          {% else %}
            <p class="text-white text-center">Nenhum horário cadastrado</p>
          {% endif %}
      </section>
    {% elif is_cliente_autenticado %}
      <section data-expandable-container class="p-4 flex flex-col gap-2 rounded-md">
        <h2 class="text-white text-xl">Agendamentos</h2>
        {% if meus_agendamentos %}
          <ul data-expandable-list class="flex flex-col gap-2 max-h-40 overflow-hidden transition-all">
            {% for agendamento in meus_agendamentos %}
            <li>
                {% include 'agendamentos/partials/appointment_card.html' with date=agendamento.horario.data_inicio|date:"d/m" start_time=agendamento.horario.data_inicio|date:"H:i" end_time=agendamento.horario.data_fim|date:"H:i" %}
              </li>
            {% endfor %}
          </ul>
          {% if meus_agendamentos|length > MAX_ITENS_CONTAINER_EXPANSIVEL %}
            <div class="flex w-full justify-center items-center text-sm pt-2">
              <span
                data-expandable-button
                class="text-white cursor-pointer hover:scale-105 transition-transform"
              >
                Ver Mais ↓
              </span>
            </div>
          {% endif %}
        {% else %}
          <p class="text-white text-center">Nenhum horário cadastrado</p>
        {% endif %}      
      </section>
    {% else %}
      <p class="text-white p-4">Faça login para realizar seus agendamentos</p>
    {% endif %}
</aside>

templates/partials/form-alerts.html
{% for message in messages %}
    <div role="alert" class="alert alert-error">
        <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-6 w-6 shrink-0 stroke-current"
                fill="none"
                viewBox="0 0 24 24">
            <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"/>
        </svg>
        <span>{{ message }}</span>
    </div>
{% endfor %}

templates/partials/header.html
<header class="sticky top-0 bg-primary max-sm:px-4 min-h-20 z-10">
    <div class="navbar w-auto max-w-6xl mx-auto px-12 box-content justify-between max-sm:px-4">
        <div>
            <div class="lg:hidden" data-menu-button-open>
                {% include 'icons/hamburguer_icon.html' %}
            </div>
            <a class="btn btn-ghost text-xl text-white" href="{% url 'pagina_inicial' %}">
                GetServices
            </a>
        </div>
        <nav class="navbar-center hidden lg:flex">
            <ul class="menu menu-horizontal px-1 text-white">
                {% if request.user.is_authenticated %}
                    <li>
                        <a href="{% url 'horarios_resumo' %}">Horários</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <div>
            {% if request.user.is_anonymous %}
                <a class="btn" href="{% url 'pagina_login' %}">Fazer login</a>
            {% else %}
                <form action="{% url 'pagina_logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Sair</button>
                </form>
            {% endif %}
        </div>
    </div>
</header>

templates/partials/info_card.html
<article class="flex flex-col p-4 bg-zinc-100 gap-4 rounded-md max-sm:gap-2">
    <div class="flex gap-2">
        {% if profile %}
            <img
                    class="rounded-full aspect-square"
                    src="{{ profile.url }}"
                    alt="Imagem de perfil do usuário {{ name }}"
                    width="48"
                    height="48"
            >
        {% else %}
            <div class="rounded-full aspect-square size-12 flex justify-center items-center bg-zinc-200">
                <span class="font-semibold text-lg">
                    {{ name|slice:"0:1"|upper }}
                </span>
            </div>
        {% endif %}
        <div class="w-full flex flex-col">
            <h3 class="text-xl">{{ name }}</h3>
            {% include 'partials/stars.html' with immutable=True rating=rating %}
        </div>
    </div>
    <p>{{ text }}</p>

    {% if slug %}
        <a href="{% url 'pagina_perfil' slug=slug %}" class="link link-primary">Ver perfil</a>
    {% endif %}
</article>

templates/partials/modal.html
<dialog id="criarAgendamentoModal" class="modal">
    <div class="modal-box">
        <h3 class="text-lg font-bold">Faça seu agendamento</h3>

        {% if has_horario_livre %}
            <form method="post" class="space-y-4">
                {% csrf_token %}
                <input type="hidden" name="profissional" id="id_profissional" value="{{ profissional.id }}">
                <input type="hidden" name="cliente" id="id_cliente" value="{{ user.cliente.id }}">

                <div class="form-control">
                    <div class="label">
                        <span class="label-text">Selecione um horário</span>
                    </div>

                    <select class="select select-bordered w-full" name="horario" id="id_horario">
                        {% for horario in horarios %}
                            {% if horario.vago %}
                              <option value="{{ horario.id }}">{{ horario.data_inicio|date:"d/m" }} / {{ horario.data_inicio|date:"H:i" }} - {{ horario.data_fim|date:"H:i" }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                </div>

                <input class="btn btn-primary btn-sm" type="submit" name="criar_agendamento"/>
            </form>
        {% else %}
            <span>Não há horário disponíveis no momento. Tente novamente mais tarde.</span>
        {% endif %}

        <form method="dialog" class="flex justify-end">
            <button class="btn btn-sm">Cancelar</button>
        </form>
    </div>
</dialog>

templates/partials/stars.html
{% if size %}
<div class="rating gap-0.5">
    {% if immutable %}
        {% for number in 12345|make_list %}
            {% if rating|stringformat:"i" >= number %}
                <span class="mask mask-star-2 bg-orange-400 size-{{ size }}"></span>
            {% else %}
                <span class="mask mask-star-2 bg-orange-400 size-{{ size }} opacity-20"></span>
            {% endif %}
        {% endfor %}
    {% else %}
        <span class="mask mask-star-2 bg-orange-400 size-{{ size }}"></span>
        <span class="mask mask-star-2 bg-orange-400 size-{{ size }}"></span>
        <span class="mask mask-star-2 bg-orange-400 size-{{ size }}"></span>
        <span class="mask mask-star-2 bg-orange-400 size-{{ size }}"></span>
        <span class="mask mask-star-2 bg-orange-400 size-{{ size }}"></span>
    {% endif %}
</div>
{% else %}
<div class="rating gap-0.5">
    {% if immutable %}
        {% for number in 12345|make_list %}
            {% if rating|stringformat:"i" >= number %}
                <span class="mask mask-star-2 bg-orange-400 size-4"></span>
            {% else %}
                <span class="mask mask-star-2 bg-orange-400 size-4 opacity-20"></span>
            {% endif %}
        {% endfor %}
    {% else %}
        <span class="mask mask-star-2 bg-orange-400 size-4"></span>
        <span class="mask mask-star-2 bg-orange-400 size-4"></span>
        <span class="mask mask-star-2 bg-orange-400 size-4"></span>
        <span class="mask mask-star-2 bg-orange-400 size-4"></span>
        <span class="mask mask-star-2 bg-orange-400 size-4"></span>
    {% endif %}
</div>

{% endif %}