core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("usuarios.urls")),
    path("", include("servicos.urls")),
    path("", include("agendamentos.urls")),
    path("avaliacoes/", include("avaliacoes.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    from debug_toolbar.toolbar import debug_toolbar_urls

    urlpatterns += debug_toolbar_urls()

usuarios/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import LoginView, PerfilProfissionalView, RegistrarView

urlpatterns = [
    path("cadastrar", RegistrarView.as_view(), name="pagina_cadastro"),
    path("login", LoginView.as_view(), name="pagina_login"),
    path("logout", LogoutView.as_view(), name="pagina_logout"),
    path("perfil/<slug:slug>/", PerfilProfissionalView.as_view(), name="pagina_perfil"),
]

agendamentos/models.py
from datetime import datetime, timedelta

from dateutil.rrule import DAILY, MONTHLY, WEEKLY, rrule
from django.db import models
from django.utils import timezone


class Agendamento(models.Model):
    profissional = models.ForeignKey(
        "usuarios.Profissional",
        on_delete=models.CASCADE,
    )
    cliente = models.ForeignKey(
        "usuarios.Cliente",
        on_delete=models.CASCADE,
    )
    horario = models.ForeignKey("Horario", on_delete=models.CASCADE)
    status_choices = (
        ("Pendente", "Pendente"),
        ("Concluido", "Concluido"),
        ("Cancelado", "Cancelado"),
    )
    status = models.CharField(
        max_length=9,
        choices=status_choices,
        default="Pendente",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.profissional.servico.nome} - {self.cliente}"


class Horario(models.Model):
    profissional = models.ForeignKey(
        "usuarios.Profissional",
        on_delete=models.CASCADE,
    )
    data_inicio = models.DateTimeField()
    data_fim = models.DateTimeField()
    vago = models.BooleanField(default=True)

    FREQUENCIA_CHOICES = [
        ("UNICA", "Não se repete"),
        ("DIARIA", "Todos os dias"),
        ("SEMANAL", "Semanalmente"),
        ("MENSAL", "Mensalmente"),
    ]
    frequencia = models.CharField(
        max_length=10,
        choices=FREQUENCIA_CHOICES,
        default="UNICA",
    )

    dias_semana = models.CharField(max_length=13, blank=True, null=True)
    data_fim_recorrencia = models.DateField(null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.data_inicio}"

    def gerar_horarios_recorrentes(self):
        if self.frequencia == "UNICA":
            return [self]

        duracao = self.data_fim - self.data_inicio

        proximo_ano = (self.data_inicio + timedelta(days=365)).date()

        data_fim_recorrencia = self.data_fim_recorrencia or proximo_ano

        if self.data_inicio.tzinfo is None:
            self.data_inicio = timezone.make_aware(self.data_inicio)

        if self.data_fim.tzinfo is None:
            self.data_fim = timezone.make_aware(self.data_fim)

        data_fim_recorrencia = timezone.make_aware(
            datetime.combine(data_fim_recorrencia, self.data_inicio.time()),
        )

        if self.frequencia == "DIARIA":
            datas = list(
                rrule(DAILY, dtstart=self.data_inicio, until=data_fim_recorrencia),
            )
        elif self.frequencia == "SEMANAL":
            dias_semana = (
                [int(dia) for dia in self.dias_semana.split(",")]
                if self.dias_semana
                else None
            )
            datas = list(
                rrule(
                    WEEKLY,
                    dtstart=self.data_inicio,
                    until=data_fim_recorrencia,
                    byweekday=dias_semana,
                ),
            )
        elif self.frequencia == "MENSAL":
            datas = list(
                rrule(MONTHLY, dtstart=self.data_inicio, until=data_fim_recorrencia),
            )
        else:
            return []

        horarios_recorrentes = [
            Horario(
                profissional=self.profissional,
                data_inicio=data,
                data_fim=data + duracao,
                vago=True,
                frequencia="UNICA",
            )
            for data in datas[1:]
        ]

        return horarios_recorrentes

usuarios/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.text import slugify


class BaseUser(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    profile_image = models.FileField(upload_to="users/%y/%m/%d", null=True, blank=True)

    @property
    def name(self):
        return f"{self.first_name} {self.last_name}"


class Cliente(models.Model):
    user = models.OneToOneField(BaseUser, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return "Cliente: " + self.user.username


class Profissional(models.Model):
    user = models.OneToOneField(BaseUser, on_delete=models.CASCADE)
    servico = models.ForeignKey("servicos.Servico", on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True, null=True)
    descricao = models.TextField()

    class Meta:
        verbose_name_plural = "Profissionais"

    def __str__(self) -> str:
        return "Profissional: " + self.user.username

    def save(
        self,
        force_insert=False,
        force_update=False,
        using=None,
        update_fields=None,
    ):
        self.slug = slugify(self.user.username)
        super().save(force_insert, force_update, using, update_fields)

usuarios/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from usuarios.models import BaseUser


class RegistrarForm(UserCreationForm):
    tipo_usuario = forms.ChoiceField(
        choices=[("cliente", "Cliente"), ("profissional", "Profissional")],
    )

    class Meta:
        model = BaseUser
        fields = [
            "username",
            "first_name",
            "last_name",
            "password1",
            "password2",
            "tipo_usuario",
        ]


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label="Usuário",
        widget=forms.TextInput(
            attrs={
                "class": "input input-bordered w-full",
                "placeholder": "ruangustavo",
            },
        ),
    )
    password = forms.CharField(
        label="Senha",
        widget=forms.PasswordInput(
            attrs={"class": "input input-bordered w-full", "placeholder": "********"},
        ),
    )

usuarios/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.views import LoginView as DjangoLoginView
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView

from agendamentos import selectors as agendamentos_selectors
from agendamentos.forms import AgendamentoForm
from agendamentos.models import Agendamento
from avaliacoes import selectors as avaliacoes_selectors
from avaliacoes.forms import AvaliacaoForm
from avaliacoes.models import Avaliacao
from core.views import BaseUsuarioAutenticadoView
from servicos.models import Servico

from .forms import LoginForm, RegistrarForm
from .models import Cliente, Profissional


class PerfilProfissionalView(View, BaseUsuarioAutenticadoView):
    model = Profissional
    template_name = "perfil.html"

    def get_context_data(self, slug, request):
        profissional = Profissional.objects.select_related("user").get(slug=slug)

        pode_avaliar = self.usuario_pode_avaliar(profissional, usuario=request.user)

        avaliacoes = self.get_avaliacoes_data(profissional)
        schedule_data = agendamentos_selectors.get_profissional_schedule(profissional)
        horarios = schedule_data["horarios"]

        profissional_autenticado = self.get_profissional_autenticado()
        cliente_autenticado = self.get_cliente_autenticado()

        context = {
            "profissional": profissional,
            "pode_avaliar": pode_avaliar,
            "has_horario_livre": any(horario.vago for horario in horarios),
            "agendamentos": schedule_data["agendamentos"],
            "avaliacoes": avaliacoes["avaliacoes"],
            "horarios": horarios,
            "is_profissional_autenticado": bool(profissional_autenticado),
            "is_cliente_autenticado": bool(cliente_autenticado),
            **avaliacoes,
        }

        if profissional_autenticado:
            schedule_data = agendamentos_selectors.get_profissional_schedule(
                profissional_autenticado
            )
            context["meus_agendamentos"] = schedule_data["agendamentos"]
            context["meus_horarios"] = schedule_data["horarios"]
        elif cliente_autenticado:
            context["meus_agendamentos"] = agendamentos_selectors.get_cliente_schedule(
                cliente_autenticado
            )["agendamentos"]

        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(self.kwargs.get("slug"), request)
        return render(request, self.template_name, context)

    def post(self, request, slug):
        profissional = get_object_or_404(Profissional, slug=slug)
        cliente = Cliente.objects.get(user=request.user)
        context = self.get_context_data(slug, request)

        if request.POST.get("avaliacao_comentario") and context["pode_avaliar"]:
            form = AvaliacaoForm(request.POST)

            if form.is_valid():
                avaliacao = form.save(commit=False)
                avaliacao.cliente = cliente
                avaliacao.profissional = profissional
                avaliacao.agendamento = Agendamento.objects.filter(
                    cliente=cliente, profissional=profissional, status="Concluido"
                ).first()
                avaliacao.save()
                return redirect("pagina_perfil", slug=profissional.slug)

        if request.POST.get("criar_agendamento"):
            form = AgendamentoForm(request.POST)

            if form.is_valid():
                form.instance.horario.vago = False
                form.instance.horario.save()
                form.save()
                return redirect("pagina_inicial")

        return render(request, self.template_name, context)

    def get_avaliacoes_data(self, profissional):
        avaliacoes = avaliacoes_selectors.get_avaliacoes(profissional)

        avaliacoes_notas = (
            avaliacoes["avaliacoes"]
            .values("nota")
            .annotate(count=Count("id"))
            .order_by("-nota")
        )

        avaliacoes_existentes = {
            item["nota"]: item["count"] for item in avaliacoes_notas
        }

        todas_avaliacoes = [
            {"nota": nota, "count": avaliacoes_existentes.get(nota, 0)}
            for nota in range(1, 6)
        ]

        todas_avaliacoes.sort(key=lambda x: x["nota"], reverse=True)

        total_avaliacoes = len(avaliacoes["avaliacoes"])
        media_avaliacao = avaliacoes["media_avaliacao"]

        return {
            "avaliacoes": avaliacoes["avaliacoes"],
            "media_avaliacao": media_avaliacao,
            "avaliacoes_notas": todas_avaliacoes,
            "total_avaliacoes": total_avaliacoes,
        }

    def usuario_pode_avaliar(self, profissional, usuario):
        if usuario.is_anonymous:
            return False

        cliente = Cliente.objects.filter(user=usuario).first()

        if cliente is None or profissional.user == usuario:
            return False

        agendamento = Agendamento.objects.filter(
            cliente=cliente, profissional=profissional, status="Concluido"
        ).first()

        pode_avaliar = (
            agendamento is not None
            and not Avaliacao.objects.filter(
                agendamento=agendamento, cliente=cliente
            ).exists()
        )

        return pode_avaliar


class RegistrarView(CreateView):
    form_class = RegistrarForm
    template_name = "pagina_cadastro.html"
    success_url = reverse_lazy("pagina_login")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["servicos"] = Servico.objects.all()
        return context

    def form_valid(self, form):
        usuario = form.save()

        tipo_usuario = self.request.POST.get("tipo_usuario")

        if tipo_usuario == "cliente":
            Cliente.objects.create(user=usuario)
        elif tipo_usuario == "profissional":
            servico_id = self.request.POST.get("servico")
            descricao = self.request.POST.get("descricao")

            if servico_id:
                servico = Servico.objects.get(id=servico_id)
                Profissional.objects.create(
                    user=usuario, servico=servico, descricao=descricao
                )

        login(self.request, usuario)
        return super().form_valid(form)

    def form_invalid(self, form):
        for errors in form.errors.values():
            for error in errors:
                messages.error(self.request, error)
        return super().form_invalid(form)


class LoginView(DjangoLoginView):
    form_class = LoginForm
    template_name = "pagina_login.html"

    def form_invalid(self, form):
        messages.error(self.request, "Nome de usuário ou senha inválidos.")
        return super().form_invalid(form)

usuarios/templates/pagina_cadastro.html
{% extends 'layout/base.html' %}

{% block content %}
    <div class="w-full">
        <div class="card card-bordered">
            <div class="card-body">
                <h1 class="card-title">Faça seu cadastro</h1>
                {% include 'partials/form-alerts.html' with messages=messages %}

                <form method="post" class="space-y-4">
                    {% csrf_token %}

                    <div class="space-y-2">
                        <span class="label-text">Eu sou</span>

                        <div class="form-control">
                            <label class="flex items-center gap-1.5 cursor-pointer">
                                <input type="radio" name="tipo_usuario" value="cliente"
                                       class="radio radio-primary radio-sm"
                                       checked="checked"/>
                                <span class="label-text">Cliente</span>
                            </label>
                        </div>
                        <div class="form-control">
                            <label class="flex items-center gap-1.5 cursor-pointer">
                                <input type="radio" name="tipo_usuario" value="profissional"
                                       class="radio radio-primary radio-sm"/>
                                <span class="label-text">Profissional</span>
                            </label>
                        </div>
                    </div>

                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">Usuário</span>
                        </div>
                        <input type="text" name="username" placeholder="ruangustavo"
                               class="input input-bordered w-full"/>
                    </label>

                    <div class="grid grid-cols-1 md:grid-cols-2 md:gap-2">
                        <label class="form-control w-full">
                            <div class="label">
                                <span class="label-text">Nome</span>
                            </div>
                            <input type="text" name="first_name" placeholder="Ruan"
                                   class="input input-bordered w-full"/>
                        </label>

                        <label class="form-control w-full">
                            <div class="label">
                                <span class="label-text">Sobrenome</span>
                            </div>
                            <input type="text" name="last_name" placeholder="Gustavo"
                                   class="input input-bordered w-full"/>
                        </label>
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-2 md:gap-2">
                        <label class="form-control w-full">
                            <div class="label">
                                <span class="label-text">Senha</span>
                            </div>
                            <input type="password" name="password1" placeholder="********"
                                   class="input input-bordered w-full"/>
                        </label>

                        <label class="form-control w-full">
                            <div class="label">
                                <span class="label-text">Confirme sua senha</span>
                            </div>
                            <input type="password" name="password2" placeholder="********"
                                   class="input input-bordered w-full"/>
                        </label>
                    </div>

                    <div id="profissional_fields" class="hidden">
                        <div class="label">
                            <label for="servico" class="label-text">Serviço oferecido</label>
                        </div>
                        <select name="servico" id="servico" class="select select-bordered w-full">
                            <option disabled selected>Selecione um serviço</option>
                            {% for servico in servicos %}
                                <option value="{{ servico.id }}">{{ servico.nome }}</option>
                            {% endfor %}
                        </select>

                        <div class="label">
                            <label for="descricao" class="label-text">Descrição</label>
                        </div>
                        <textarea name="descricao" id="descricao" class="textarea textarea-bordered w-full"
                                  placeholder="Fale um pouco sobre você e os serviços que oferece. Que tipo de trabalho você faz? Como você pode ajudar as pessoas? Descreva sua experiência e habilidades com o seu ofício."></textarea>
                    </div>

                    <button type="submit" class="btn btn-primary block">Cadastrar</button>
                </form>
            </div>
        </div>
    </div>

    <script>
        const radioButtons = document.querySelectorAll('input[name="tipo_usuario"]');
        const clienteFields = document.getElementById('profissional_fields');

        radioButtons.forEach(radio => {
            radio.addEventListener('change', () => {
                if (document.querySelector('input[name="tipo_usuario"]:checked').value === 'profissional') {
                    clienteFields.classList.remove('hidden');
                } else {
                    clienteFields.classList.add('hidden');
                }
            });
        });
    </script>
{% endblock %}

usuarios/templates/pagina_login.html
{% extends 'layout/base.html' %}

{% block content %}
    <div class="w-full">
        <div class="card card-bordered">
            <div class="card-body">
                <h1 class="card-title">Faça seu login</h1>

                {% include 'partials/form-alerts.html' with error=message %}

                <form method="post" class="space-y-4">
                    {% csrf_token %}

                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">{{ form.username.label }}</span>
                        </div>
                        {{ form.username }}
                    </label>

                    <label class="form-control w-full">
                        <div class="label">
                            <span class="label-text">{{ form.password.label }}</span>
                        </div>
                        {{ form.password }}
                    </label>

                    <div class="card-actions items-center justify-between">
                        <button type="submit" class="btn btn-primary block">Entrar</button>
                        <a href="{% url 'pagina_cadastro' %}">Não tenho conta</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

usuarios/templates/perfil.html
{% extends 'layout/base.html' %}
{% load static %}

{% block title %}
    {{ profissional.user.username }} - {{ profissional.servico.nome }}
{% endblock title %}

{% block head %}
    <script src="{% static 'js/appointments.js' %}" defer></script>
{% endblock %}

{% block content %}
    <div class="bg-[url('https://www.simplilearn.com/ice9/free_resources_article_thumb/IsGraphic_DesignAGoodCareerb.jpg')] bg-center h-80 w-full absolute top-20 left-0 bg-no-repeat bg-cover -z-10"></div>
    <main class="w-full mt-52">
        <article class="bg-zinc-100 p-8 rounded-md flex gap-8">
            <div class="w-full flex gap-4 max-md:flex-col">
                <div class="flex flex-col justify-start items-center gap-4 max-md:flex-row max-md:items-start">
                    <img class="rounded-md size-36"
                         src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
                         alt="User profile image">
                    <div class="flex flex-col gap-1">
                        <h2 class="text-xl font-bold text-black md:hidden">{{ profissional.user.username }}</h2>
                        <span class="text-sm">{{ profissional.servico.nome }}</span>
                        <div class="flex justify-center gap-1 max-md:justify-start">
                            <span class="inline-block mask mask-star-2 bg-orange-400 size-4"></span>
                            <span class="text-sm">{{ media_avaliacao|floatformat:1 }} / 5,0</span>
                        </div>
                    </div>
                </div>
                <div class="flex flex-col justify-start items-start gap-2">
                    <h2 class="text-xl font-bold text-black max-md:hidden">{{ profissional.user.username }}</h2>
                    <p>{{ profissional.servico.descricao }}</p>
                </div>
            </div>
            <div class="flex justify-center items-center min-w-max max-lg:hidden">
                {% include 'partials/ratings.html' %}
            </div>
        </article>
        <div class="flex gap-6 mt-8 max-lg:flex-col">
            <div class="relative">
                <aside class="min-w-72 flex flex-col gap-4 sticky top-24 max-h-[calc(100vh-7rem)]">
                    <section data-expandable-container class="p-4 bg-blue-500 rounded-md">
                        <ul class="mb-4">
                            <li class="flex justify-start items-center gap-2">
                                <div class="w-full flex p-3 rounded-md justify-between items-center bg-primary">
                                    <div class="flex items-center">
                                        {% include 'icons/email.html' %}
                                        <span class="text-white ml-1">admin@email.com</span>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        <ul data-expandable-list
                            class="flex flex-col gap-2 max-h-40 overflow-hidden transition-all duration-300 ease-in-out">
                            {% for horario in horarios %}
                                <li {% if not horario.vago %} class="cursor-not-allowed opacity-50" {% endif %}>
                                    {% include 'agendamentos/partials/schedule_card.html' with date=horario.data_inicio|date:"d/m" start_time=horario.data_inicio|date:"H:i" end_time=horario.data_fim|date:"H:i" %}
                                </li>
                            {% endfor %}
                        </ul>
                        {% if horarios|length > MAX_ITENS_CONTAINER_EXPANSIVEL %}
                            <div class="flex w-full justify-center items-center text-sm pt-2">
                            <span data-expandable-button
                                  class="text-white cursor-pointer hover:scale-105 transition-transform">Ver Mais ↓</span>
                            </div>
                        {% endif %}
                    </section>
                    <section data-expandable-container class="p-4 bg-blue-500 rounded-md">
                        <div class="flex justify-between mb-4">
                            <span class="text-white text-xl">Agendamentos</span>
                            {% if user != profissional.user %}
                                <button onclick="criarAgendamentoModal.showModal()" class="btn btn-circle btn-sm">
                                    &plus;
                                </button>
                            {% endif %}
                        </div>
                        <ul data-expandable-list
                            class="flex flex-col gap-2 max-h-40 overflow-hidden transition-all duration-300 ease-in-out">
                            {% for agendamento in agendamentos %}
                                <li data-appointment-container>
                                    <span class="relative z-10">
                                        {% include 'agendamentos/partials/appointment_card.html' with date=agendamento.horario.data_inicio|date:"d/m" start_time=agendamento.horario.data_inicio|date:"H:i" end_time=agendamento.horario.data_fim|date:"H:i" %}
                                    </span>
                                    {% if agendamento.status == "Pendente" and agendamento.profissional.user == user %}
                                        <form class="bg-blue-400 rounded-b-md h-8 relative -top-1 flex justify-start items-center gap-2 px-4"
                                              action="{% url 'responder_agendamento' agendamento.id %}" method="post">
                                            {% csrf_token %}
                                            <input class="hidden" data-approve-input type="radio" name="status"
                                                   id="id_status" value="Concluido">
                                            <input class="hidden" data-cancel-input type="radio" name="status"
                                                   id="id_status" value="Cancelado">
                                            <span class="cursor-pointer text-blue-800" data-approve-appointment>
                                                Aceitar
                                            </span>
                                            <span class="cursor-pointer text-blue-800" data-cancel-appointment>
                                                Negar
                                            </span>
                                        </form>
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                        {% if agendamentos|length > MAX_ITENS_CONTAINER_EXPANSIVEL %}
                            <div class="flex w-full justify-center items-center text-sm pt-2">
                            <span data-expandable-button
                                  class="text-white cursor-pointer hover:scale-105 transition-transform">Ver Mais ↓</span>
                            </div>
                        {% endif %}
                    </section>
                </aside>
            </div>
            <section class="flex flex-col gap-4 grow">
                {% if pode_avaliar %}
                    <article class="flex flex-col p-4 bg-zinc-100 gap-4 rounded-md max-sm:gap-2">
                        <form method="post" class="flex flex-col gap-4">
                            {% csrf_token %}
                            <label for="nota" class="form-control">
                                <div class="label inline">
                                    <span class="label-text">Nota</span>
                                </div>

                                <div class="rating">
                                    <input type="radio" value="1" name="nota" class="bg-orange-400 mask mask-star-2"
                                           checked="checked"/>
                                    <input type="radio" value="2" name="nota" class="bg-orange-400 mask mask-star-2"/>
                                    <input type="radio" value="3" name="nota" class="bg-orange-400 mask mask-star-2"/>
                                    <input type="radio" value="4" name="nota" class="bg-orange-400 mask mask-star-2"/>
                                    <input type="radio" value="5" name="nota" class="bg-orange-400 mask mask-star-2"/>
                                </div>
                            </label>

                            <label class="form-control" for="comentario">
                            <textarea
                                    name="comentario"
                                    placeholder="Conte-nos como foi sua experiência. O que você achou do serviço prestado? O profissional atendeu suas expectativas? Como o trabalho realizado impactou suas necessidades? Compartilhe detalhes que possam ajudar outras pessoas a entenderem a qualidade do serviço."
                                    class="textarea textarea-bordered min-h-40"></textarea>
                            </label>
                            <div class="flex justify-end">
                                <input name="avaliacao_comentario" type="submit" class="btn btn-primary btn-sm"/>
                            </div>
                        </form>

                    </article>
                {% endif %}

                {% for avaliacao in avaliacoes %}
                    {% include 'partials/info_card.html' with name=avaliacao.cliente.user.username rating=avaliacao.nota text=avaliacao.comentario %}
                {% endfor %}

            </section>
        </div>
    </main>
    {% include 'partials/modal.html' %}
{% endblock %}